version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 15
    allow:
      - dependency-name: "*"
        dependency-type: "development"
      - dependency-name: "protobuf"
        dependency-type: "production"
      - dependency-name: "six"
        dependency-type: "production"
